precedence: 3
name: "release"
target: "branch"
source_type: "Repository"
source: "{{REPO}}"
enforcement: "active"
conditions:
  ref_name:
    exclude: []
    include:
      - "refs/heads/release"
rules:
  - type: "deletion"
  - type: "non_fast_forward"
  - type: "pull_request"
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: true
      require_last_push_approval: false
      required_review_thread_resolution: true
      automatic_copilot_code_review_enabled: true
      allowed_merge_methods:
        - "merge"
        - "squash"
        - "rebase"
  - type: "required_status_checks"
    parameters:
      strict_required_status_checks_policy: true
      do_not_enforce_on_create: false
      required_status_checks:
        - context: "Analyze (go)"
          integration_id: 15368
bypass_actors: [] 