precedence: 3
name: "release"
target: "branch"
source_type: "Repository"
source: "{{REPO}}"
enforcement: "active"
conditions:
  ref_name:
    exclude: []
    include:
      - "refs/heads/release"
rules:
  - type: "deletion"
  - type: "non_fast_forward"
  - type: "pull_request"
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: true
      require_last_push_approval: false
      required_review_thread_resolution: true
      automatic_copilot_code_review_enabled: true
      allowed_merge_methods:
        - "squash"
  - type: "required_status_checks"
    parameters:
      strict_required_status_checks_policy: true
      do_not_enforce_on_create: false
      required_status_checks:
        - context: "Analyze (go)"
          integration_id: 15368
  - type: "commit_message_pattern"
    parameters:
      operator: "regex"
      pattern: "^(feat|fix|docs|style|refactor|test|chore|ci|perf|revert)(\\([a-z0-9-]+\\))?: .*"
      negate: false
      name: "Must follow conventional commits format"
bypass_actors:
  - actor_id: null
    actor_type: "EnterpriseOwner"
    bypass_mode: "pull_request"
  - actor_id: null
    actor_type: "DeployKey"
    bypass_mode: "always"
  - actor_id: null
    actor_type: "OrganizationAdmin"
    bypass_mode: "pull_request"
  - actor_id: 5
    actor_type: "RepositoryRole"
    bypass_mode: "pull_request"
  - actor_id: 11534793
    actor_type: "Team"
    bypass_mode: "pull_request" 