name: release-please
on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
          target-branch: release
          config-file: .github/release-please-config.json

      - name: Update version.go
        if: ${{ steps.release.outputs.release_created }}
        run: |
          # Checkout the release-please branch
          git fetch origin release-please--branches--release
          git checkout release-please--branches--release
          # Remove 'v' prefix from version
          VERSION=${steps.release.outputs.tag_name#v}
          # Update version.go
          sed -i "s/const Version = \".*\"/const Version = \"v${VERSION}\"/" version.go
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Add and commit changes
          git add version.go
          git commit -m "chore: update version.go to ${steps.release.outputs.tag_name}"
          # Push changes to release-please branch
          git push origin release-please--branches--release 