name: release-please
on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write
  metadata: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          target-branch: release
          config-file: .github/release-please-config.json 